# Code from Dave C.

In [2]:
import pandas as pd

In [3]:
filename = 'data\\validTypes.csv'
df = pd.read_csv(filename)

In [4]:
df

,A111,A112,A121,A122,A131,A132,A141,A142,A151,A152,...,A171,A172,A241,A242,A251,A252,A261,A262,A271,A272
0,20-Yr A,Uncommitted,20-Yr A,Uncommitted,10-Yr,Uncommitted,20-Yr A,Uncommitted,20-Yr A,Uncommitted,...,20-Yr A,Uncommitted,FST,Uncommitted,FST,Uncommitted,FST,Uncommitted,FST,Uncommitted
1,20-Yr B,NaN,20-Yr B,NaN,20-Yr,NaN,20-Yr B,Uncommitted (IJT),20-Yr B,Uncommitted (IJT),...,20-Yr B,Uncommitted (IJT),ST-A,NaN,ST-A,NaN,ST-A,NaN,ST-A,NaN
2,Temporary Diversion from Cushing,NaN,Temporary Diversion from Cushing,NaN,Permanent Diversion from Patoka,NaN,Permanent Diversion from Cushing,NaN,Permanent Diversion from Cushing,NaN,...,Permanent Diversion from Cushing,NaN,ST-B,NaN,ST-B,NaN,ST-B,NaN,ST-B,NaN
3,Excess,NaN,Excess,NaN,Temporary Diversion from Patoka 20-Yr A,NaN,Temporary Diversion from Patoka 20-Yr A,NaN,Temporary Diversion from Patoka 20-Yr A,NaN,...,Temporary Diversion from Patoka 20-Yr A,NaN,2B,NaN,2B,NaN,2B,NaN,2B,NaN
4,NaN,NaN,NaN,NaN,Temporary Diversion from Patoka 20-Yr B,NaN,Temporary Diversion from Patoka 20-Yr B,NaN,Temporary Diversion from Patoka 20-Yr B,NaN,...,Temporary Diversion from Patoka 20-Yr B,NaN,2C,NaN,2C,NaN,2C,NaN,2C,NaN
5,NaN,NaN,NaN,NaN,Excess,NaN,Excess,NaN,Excess,NaN,...,Excess,NaN,5,NaN,5,NaN,5,NaN,5,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6A,NaN,6A,NaN,6A,NaN,6A,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,6B,NaN,6B,NaN,6B,NaN,6B,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,7,NaN,7,NaN,7,NaN,7,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LT-A,NaN,LT-A,NaN,LT-A,NaN,LT-A,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LT-B,NaN,LT-B,NaN,LT-B,NaN,LT-B,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,LT-C,NaN,LT-C,NaN,LT-C,NaN,LT-C,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Excess,NaN,Excess,NaN,Excess,NaN,Excess,NaN

In [5]:
filename = 'data\\masterTypes.csv'
df2 = pd.read_csv(filename)

In [6]:
df2

                            Type of Service  ID_Type of Service
0                                     10-Yr                   1
1                                     20-Yr                   2
2                                   20-Yr A                   3
3                                   20-Yr B                   4
4           Permanent Diversion from Patoka                   5
5          Permanent Diversion from Cushing                   6
6          Temporary Diversion from Cushing                   7
7   Temporary Diversion from Patoka 20-Yr A                   8
8   Temporary Diversion from Patoka 20-Yr B                   9
9                               Uncommitted                  10
10                        Uncommitted (IJT)                  11
11                                   Excess                  12
12                                      FST                  13
13                                     ST-A                  14
14                                     ST-B                  15
15                                       2B                  16
16                                       2C                  17
17                                        5                  18
18                                       6A                  19
19                                       6B                  20
20                                        7                  21
21                                     LT-A                  22
22                                     LT-B                  23
23                                     LT-C                  24

In [22]:
returnBody = ''

myKey = 'A141'
myColumn = df.loc[:, myKey]

In [23]:
merged = pd.merge(df,df2,left_on='A141', right_on='Type of Service', how='inner')

In [32]:
# select multiple columns
selected = merged[['A141','Type of Service', 'ID_Type of Service']]
selected.to_json(orient='records')

'[{"A141":"20-Yr A","Type of Service":"20-Yr A","ID_Type of Service":3},{"A141":"20-Yr B","Type of Service":"20-Yr B","ID_Type of Service":4},{"A141":"Permanent Diversion from Cushing","Type of Service":"Permanent Diversion from Cushing","ID_Type of Service":6},{"A141":"Temporary Diversion from Patoka 20-Yr A","Type of Service":"Temporary Diversion from Patoka 20-Yr A","ID_Type of Service":8},{"A141":"Temporary Diversion from Patoka 20-Yr B","Type of Service":"Temporary Diversion from Patoka 20-Yr B","ID_Type of Service":9},{"A141":"Excess","Type of Service":"Excess","ID_Type of Service":12}]'

In [25]:
for items in myColumn.iteritems():
    row = df2.loc[df2['Type of Service'] == items[1]]
    # print (row)
    if not(row.empty):  
        # print(row.iloc[0]['Type of Service'], row.iloc[0]['ID_Type of Service']);
        returnBody = returnBody + '<Option value="{}">{}</Option>\n'.format(row.iloc[0]['ID_Type of Service'],row.iloc[0]['Type of Service'])

print(returnBody)

<Option value="3">20-Yr A</Option>
<Option value="4">20-Yr B</Option>
<Option value="6">Permanent Diversion from Cushing</Option>
<Option value="8">Temporary Diversion from Patoka 20-Yr A</Option>
<Option value="9">Temporary Diversion from Patoka 20-Yr B</Option>
<Option value="12">Excess</Option>